# Generated by Django 2.2.13 on 2022-06-22 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='city',
        ),
    ]
